
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/emp?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  #mapper-locations: classpath:mapper/*Mapper.xml
server:
  port: 8080
logging:
  level:
    root: info
